language: python
python:
- 3.6
matrix:
  include:
  - sudo: required
    python: 3.6
  - os: osx
    python: 3.6
install:
- pip install "cython>=0.29"
- pip install -e ".[tests, docs]"
script:
- pytest -vs --cov=imagededup --cov-report xml --show-capture=no tests
- cd mkdocs && sh build_docs.sh
deploy:
  matrix:
  - provider: pages
    skip_cleanup: true
    github_token: "$GITHUB_TOKEN"
    local-dir: docs/
    on:
      branch: master
    target_branch: gh-pages
  - provider: pypi
    user: __token__
    password:
      secure: QR6kxnmUfui/DcsUAe0wkKxno/za8JebTi+B9OQSXJoX3EBQQ9t+rKZSYp4kjOnMUseIYzfyoFdTnWXJb3m0pExcFDiMOPqLVwIakUy/2uKp6UndkYNxunL1MbseCUGY8Ad6TMLfH/1WfhtoJGYCrmY/fVZUEGNbXPxH6RXYz83KjXzdej3HLOmDTDfakOnJ8FgpXKlYNoNAJR/yJmUpJt/Kox8pVeH/MkgNvPS/nNNDhXSncxp60f3p/4e23HDS97WBz9thqhPOxERJ29pXfHuboJp4Ka+HPcW0LsTAa27yeIsbaTknkhKvH/21W0qzWoEX5i02AG6RcabLUYPThWLUCfdHnHXHrNE9I5NbhqhrMt4cBrTAfQmo0RTKGxD+bX8rF7bdXSLgYm+oDUU34PqliJ65f6+pynMbWwv6cX2TgqGBSzvwHe7jBoh7ZQrEKORa5t2VHFg+Wg8YtAb3CoLFUqvoC4vqxqTttJgxReMLRT7sZk8ji3o4IcSOj02BbPB69aT2NGbGNMYNDkK63574HZsfmt4CRyQFKO40hHbVj3Brd5Ln1XCCEo0/IbXvyHrQX0NUW5ssgCdTzZccExcD571NaWPObNbHfQ/AgJrBbU19a9IFfr87II2vVcmc+wPugtV4B6zQKY2ZEyH7emHnnUg01QXqv9x33ESs2no=
    server: https://test.pypi.org/index
    on:
      branch: Incopro-feature/cython
env:
  global:
    secure: B4R9l1PzY00r/ITZfuIPunpbpMJuSrtegEyZCgy8JE/ei2sWZ0+FJ1SVausYY/g0aDumwMGITSQo6L0RafTbIG8LZ/l6KO9GuGmPsn8vYCwGd+4/eyt6nNocyGPv/4Vmm8jrgPtjUCCSGBD6mfU4nPn6bfN8Xhwl5i5ZodfXg6TfLNpYNkyauHm4L63UT6usfQ1JSE7pHb3gM88acYpTowrBm2WomgPPbKsd2isPtHbiIbOemXVpUjqygTXn7Gf8Dkq0Irasm93M3n+svAuGrhQRqfAupVlv5u+0jwQXAWhxoKAXVS/wH1n+ubN79G849VX/6B84bPGbTQS4QE9LVU+UcZ2PmyWeQZEJiwqr3T+f1bSPmu31ioGaAzxyBATm7odSht2iAGw/GzvZnL4maQAN/QhZQgjdpkQKuEURyGCEZ+87gVwpP+KUZPCiPzKRndeQTa9wiJVQk6tGwcfDD4umkqmO9Hj6lXV0UdP7ruIfhUF5IFmovBucsdLR6JL9+RzlHciDJ3905kWDQSekMo+q+tapme8qeIx0EJ6M0MohS8PXqjhS38DfZ/BkFZAxpm4gDGPaLE6wz0gAQ5ObjsMReM/drn0Bo5vEzjZCSd+f+GxlGS/Hbeos4+SCtKDNrA80m5tDoghzbVyDlRG6FGJk2+HK4JB52LPtWBoTHaE=
after_success:
- codecov
