site_name: Image-dedup
site_author: idealo Data Science Team

nav:
    - Home: index.md
    # - Getting Started: start.md
    # - Examples:
      # - Cats and Dogs: examples/cats_and_dogs.md
      # - Imagenette: examples/imagenette.md
    - Documentation:
        - Evaluation:
            - Evaluation: evaluation/evaluation.md
        - Methods:
            - CNN: methods/cnn.md
            - Hashing: methods/hashing.md
        - Utils:
            - Plot duplicates: utils/plotter.md
    - Contribution: CONTRIBUTING.md
    - License: LICENSE.md
theme:
  name: 'material'
  palette:
    primary: 'red'
    accent: 'red'
  logo: 'img/logo.svg'
  favicon: 'img/favicon.ico'

repo_name: 'idealo/image-dedup'
repo_url: 'https://github.com/idealo/image-dedup'

google_analytics:
  - 'UA-137434942-2'
  - 'auto'

markdown_extensions:
  - codehilite
