site_name: Image-dedup
site_author: idealo Data Science Team

nav:
    - Home: index.md
    - User Guide:
        - Finding duplicates: user_guide/finding_duplicates.md
        - Feature generation: user_guide/feature_generation.md
        - Evaluating performance: user_guide/evaluating_performance.md
        - Plotting duplicates: user_guide/plotting_duplicates.md
    - API documentation:
        - Methods:
            - CNN: methods/cnn.md
            - Hashing: methods/hashing.md
        - Evaluation:
            - Evaluation: evaluation/evaluation.md
        - Utils:
            - Plot duplicates: utils/plotter.md
    - Contribution: CONTRIBUTING.md
    - License: LICENSE.md
theme:
  name: 'material'
  palette:
    primary: 'indigo'
    accent: 'indigo'
  logo: 'img/logo.svg'
  favicon: 'img/favicon.ico'

repo_name: 'idealo/image-dedup'
repo_url: 'https://github.com/idealo/image-dedup'

markdown_extensions:
  - codehilite
